pull_request_rules:
  - name: Automatic merge for lab PRs when CI passes
    conditions:
      - check-success=Dummy CI / dummy-test (pull_request)
      - base=main
    actions:
      merge:
        method: merge
